type AccountImprestRetirement {
active: Boolean
approvalStatus: ApprovalStatus
cashReturnAmount: BigDecimal
contentEditable: Boolean
createdAt: LocalDateTime
createdBy: User
createdById: Long
currentApprovalStage: ApprovalProcessStage
currentApprovalStageAssignedDate: LocalDateTime
currentAssignedGroup: Role
currentAssignedUserAccount: User
deletedAt: LocalDateTime
deletedBy: Long
deletedId: Long
department: Division
description: String
finalApprovedBy: User
finalApprovedByUsername: String
finalApprovedDate: LocalDateTime
id: Long
imprest: AccountImprest
isApprovalCompleted: Boolean
isDeleted: Boolean
items: [AccountImprestRetirementItem]
migrated: Boolean
post: Division
processName: String
referenceNumber: String
retirementDate: LocalDate
status: ImprestRetirementStatus
systemNumber: String
totalAmount: BigDecimal
uid: String
updatedAt: LocalDateTime
updatedBy: Long
}

type AccountImprestRetirementItem {
account: ChartOfAccount
active: Boolean
amount: BigDecimal
createdAt: LocalDateTime
createdBy: User
createdById: Long
deletedAt: LocalDateTime
deletedBy: Long
deletedId: Long
description: String
id: Long
isDeleted: Boolean
migrated: Boolean
retirement: AccountImprestRetirement
uid: String
updatedAt: LocalDateTime
updatedBy: Long
}

type AccountImprestRetirementDtoInput {
cashReturnAmount: BigDecimal
description: String
imprestUid: String!
items: [ImprestRetirementItemDtoInput]!
referenceNumber: String!
retirementDate: LocalDate!
uid: String
}

type ImprestRetirementItemDtoInput {
amount: BigDecimal!
chartOfAccountUid: String!
description: String!
uid: String
}

enum ImprestRetirementStatus {
DRAFT
POSTED
REVERSED
}

type ImprestRetirementSummaryDto {
cashReturnAmount: BigDecimal
imprestReference: String
imprestUid: String
referenceNumber: String
retirementDate: LocalDate
retirementUid: String
totalAmount: BigDecimal
}

Mutation.recordImprestRetirement(
input: ImprestRetirementDtoInput!
): Response_AccountImprestRetirement
Query.allImprestRetirements: [AccountImprestRetirement]
Query.imprestRetirementSummary(
endDate: LocalDate
startDate: LocalDate
): [ImprestRetirementSummaryDto]
Query.allImprestRetirementsPageable(
pageableParam: PageableParamInput
active: Boolean
): Page_AccountImprestRetirement