Mutation.createOrUpdateTaskCategory(
request: TaskCategoryRequestInput
): Response_TaskCategory
Mutation.deleteTaskCategory(
id: UUID
): Response_TaskCategory
Mutation.changeTaskCategoryStatus(
id: UUID
): Response_TaskCategory
Query.getAllTaskCategories: [TaskCategoryResponse]
Query.searchTaskCategories(
filter: TaskCategoryFilterInput
): [TaskCategoryResponse]
Query.findTaskCategoryById(
id: UUID
): Response_TaskCategory

type TaskCategoryRequestInput {
code: String!
description: String
id: UUID
name: String!
}

type TaskCategory {
active: Boolean
code: String!
description: String
name: String!
}

type TaskCategoryFilterInput {
active: Boolean
code: String
id: Long
name: String
uid: UUID
}

type TaskCategoryResponse {
active: Boolean
code: String
createdAt: LocalDateTime
description: String
name: String
updatedAt: LocalDateTime
uuid: UUID
}